version: '3'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: user_products
            MYSQL_USER: user_products
            MYSQL_PASSWORD: user_products
    php:
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ./application:/var/www/application
            - ./logs/application:/var/www/application/var/logs
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx